WINDOW_WIDTH = 800
WINDOW_HEIGHT = 480

CAPTURE_IMAGE_WIDTH = 400
CAPTURE_IMAGE_HEIGHT = 267

CAMERA_SCENE_NAME = 'camera'
FILE_SELECT_SCENE_NAME = 'file_select'
MOVIE_SCENE_NAME = 'movie'


RECORDING_RESOLUTION_WIDTH = 1280
RECORDING_RESOLUTION_HEIGHT = 720

INSIDE_CAMERA_HARD_DEVICE = '/dev/video-inside'
INSIDE_CAMERA_FRAME_RATE = str('30/1')
INSIDE_CAMERA_RECORDING_DEVICE = '/dev/video66'
INSIDE_CAMERA_SHOWER_DEVICE = '/dev/video77'

OUTSIDE_CAMERA_HARD_DEVICE = '/dev/video-outside'
OUTSIDE_CAMERA_FRAME_RATE = str('30/1')
OUTSIDE_CAMERA_RECORDING_DEVICE = '/dev/video88'
OUTSIDE_CAMERA_SHOWER_DEVICE = '/dev/video99'

