WINDOW_WIDTH = 800
WINDOW_HEIGHT = 480

CAMERA_SCENE_NAME = 'camera'
FILE_SELECT_SCENE_NAME = 'file_select'
MOVIE_SCENE_NAME = 'movie'


INSIDE_CAMERA_RECORDING_RESOLUTION_WIDTH = 800
INSIDE_CAMERA_RECORDING_RESOLUTION_HEIGHT = 600

INSIDE_CAMERA_HARD_DEVICE = '/dev/video-inside'
INSIDE_CAMERA_FRAME_RATE = str('30/1')
INSIDE_CAMERA_SHOWER_DEVICE = '/dev/video77'

OUTSIDE_CAMERA_RECORDING_RESOLUTION_WIDTH = 1280
OUTSIDE_CAMERA_RECORDING_RESOLUTION_HEIGHT = 720

OUTSIDE_CAMERA_HARD_DEVICE = '/dev/video-outside'
OUTSIDE_CAMERA_FRAME_RATE = str('30/1')
OUTSIDE_CAMERA_SHOWER_DEVICE = '/dev/video99'

