WINDOW_WIDTH = 800
WINDOW_HEIGHT = 480

CAMERA_SCENE_NAME = 'camera'
FILE_SELECT_SCENE_NAME = 'file_select'
MOVIE_SCENE_NAME = 'movie'


INSIDE_CAMERA_RECORDING_RESOLUTION_WIDTH = 640
INSIDE_CAMERA_RECORDING_RESOLUTION_HEIGHT = 480

INSIDE_CAMERA_HARD_DEVICE = '/dev/video-inside'
INSIDE_CAMERA_FRAME_RATE = 30

OUTSIDE_CAMERA_RECORDING_RESOLUTION_WIDTH = 640
OUTSIDE_CAMERA_RECORDING_RESOLUTION_HEIGHT = 480

OUTSIDE_CAMERA_HARD_DEVICE = '/dev/video-outside'
OUTSIDE_CAMERA_FRAME_RATE = 30

